remote_theme: pmarsceill/just-the-docs
title: NUIG Hacky Hour
description: A website to test HTML, CSS, and Jekyll comands.

permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  Essentials:
    output: true
    permalink: /:collection/:name

# Enable or disable the site search
search_enabled: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"

# Aux links for the upper right navigation
aux_links:
  "Home":
    - "/index.html"
  "About":
    - "/About.html"
  "Contact":
    - "/Contact.html"
