#+title: Experimenting with GitHub pages and Jekyll
#+author: Marco Prevedello
#+email: marco.prevedello@outlook.it

* Project description
This is a /self-learning/ project in which I aim to understand HTML, CSS, and
Jekyll (a static site generator written in ruby) at a sufficient level to be
able to create and maintain a personal blog and the [[https://nuighackyhour.github.io/][hh-nuig]] webpage (containing
blog posts, documentation, and tutorial).

I will dedicate a maximum of 10 hours a week to this project and I aim to have
the following tasks completed by <2019-04-30 Tue>.

* Collaboration
Being learning the objective of this project any form of constructive
collaboration (e.g., improvements for syntax, structure, suggestions for
resources, etc.) is welcomed.

* Folder content and structure
This project folder contain the following files:
  - Basic linux files :: ~.~, ~..~, and ~.directory~
  - .gitignore :: a list of files not under version control
  - .jekyll-metadata :: A list of files have not been modified since the last
       site build and of files that need to be rebuild.
  - Gemfile and Gemfile.lock :: Ruby files for the required gems name and
       version.
  - index.md :: The site homepage written in markdown. If and only if a /front
                matter/ in YAML is provided, Jekyll will process the file.
  - README.org :: This file.
  - _config.yml :: The basic website configuration (e.g., which css theme to
                   use, and so on)

And the following directories:
  - .git :: Git version control folder
  - _data :: Data sets for the website. For example, a ~members.yml~ file
             containing the site members' info, to which a post can refer
             without rewriting the code.
  - _drafts :: A folder for posts drafts that will not be processed
  - _includes :: Layout for website sub-parts, like the header or the comments
                 section.
  - _layouts :: Theme settings. Here is possible to alter the layout of the
                whole site or of specific types of pages
  - _posts :: Posts for the website. The posts files must have the following
              name structure ~YEAR-MONTH-DAY-title.MARKUP~
  - _site :: The built site. *This is not tracked by git* and only available locally.
